[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Add frontend env vars here if needed

[site]
  name = "ai-podcaster-speechify"
