[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "https://ai-podcaster-speechify.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_HOST = "ai-podcaster-speechify.onrender.com"
  VITE_API_PORT = "443"

[site]
  name = "ai-podcaster-speechify"